<?php
require_once 'PHPUnit/Framework.php';
require_once dirname(__FILE__).'/../src/Pex.php';

/**
 * Test class for Pex.
 * Generated by PHPUnit on 2010-03-01 at 14:18:53.
 */
class PexTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Pex
     */
    protected $object;

    /**
     * @var Http mock
     */
    protected $httpMock;

    /**
     * @var string hostname to probe
     */
    private $_host='https://testhost.com';

    /**
     * @var string username to use
     */
    private $_username='testuser';

    /**
     * @var string password to use
     */
    private $_password='testpassword';


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->httpMock = $this->getMock('Http');
        $this->object = new Pex(
                $this->httpMock,
                $this->_host,
                $this->_username,
                $this->_password);
        
    }

    

}
?>
