<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../src/Pex/Excepcions/NoSuchConfigFileException.php';
require_once dirname(__FILE__).'/../../src/Pex/Excepcions/NoSuchConfigSectionException.php';
require_once dirname(__FILE__).'/../../src/Pex/ConnectionData.php';
require_once dirname(__FILE__).'/../../src/Pex/ConnectionDataFactory.php';

/**
 * Test class for ConnectionDataFactory.
 * Generated by PHPUnit on 2010-04-26 at 14:18:05.
 */
class ConnectionDataFactoryTest extends PHPUnit_Framework_TestCase {
    /**
     * @var ConnectionDataFactory instance
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp() {
        $this->object = new ConnectionDataFactory();
    }


    /**
     * @todo Implement testCreateConnectionData().
     */
    public function testCreateConnectionData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
?>
